# Generated by Django 5.2 on 2025-05-29 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastradoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Cadastrado Por')),
            ],
            options={
                'verbose_name_plural': 'Cadastrados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Fazenda')),
            ],
            options={
                'verbose_name_plural': 'Fazendas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ClienteFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Cliente/Fornecedor')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('inf_adicionais', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.fazenda', verbose_name='Fazenda Associada')),
            ],
            options={
                'verbose_name_plural': 'Clientes/Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('itens_da_receita', models.TextField(verbose_name='Itens da Receita')),
                ('data_receita', models.DateField(verbose_name='Data da Receita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos_receita/', verbose_name='Documento Anexo')),
                ('cadastradoPor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.cadastradopor', verbose_name='Cadastrado Por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.categoria', verbose_name='Categoria da Receita')),
                ('cliente_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.clientefornecedor', verbose_name='Cliente/Fornecedor')),
                ('fazenda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.fazenda', verbose_name='Fazenda Destino')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_parcela', models.IntegerField(verbose_name='Ordem da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('status_pagamento', models.CharField(choices=[('Pendente', 'Pendente'), ('Pago', 'Pago')], default='Pendente', max_length=50, verbose_name='Status do Pagamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.receita')),
            ],
        ),
    ]
