# Generated by Django 5.2 on 2025-05-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='cadastradoPor',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='cidade',
            field=models.CharField(default='Paranavai', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='cadastrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Fazenda'),
        ),
        migrations.DeleteModel(
            name='CadastradoPor',
        ),
    ]
