# Generated by Django 5.2 on 2025-06-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0003_alter_movimentacao_data_and_more'),
        ('perfis', '0003_alter_parceiros_email_alter_parceiros_if_adicionais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='parceiros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.parceiros', verbose_name='Empresa Parceira'),
        ),
    ]
