# Generated by Django 5.2.4 on 2025-08-26 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parceiros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome da Empresa Parceira"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "if_adicionais",
                    models.TextField(
                        blank=True, null=True, verbose_name="Informações Adicionais"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="E-mail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parceiro",
                "verbose_name_plural": "Parceiros",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fazenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "usuarios",
                    models.ManyToManyField(
                        related_name="fazendas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fazenda",
                "verbose_name_plural": "Fazendas",
                "ordering": ["nome"],
            },
        ),
    ]
