# Generated by Django 5.2 on 2025-06-24 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='proprietario',
        ),
        migrations.RemoveField(
            model_name='fazenda',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='usuarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
