# Generated by Django 5.2 on 2025-06-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_remove_fazenda_proprietario_remove_fazenda_usuarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='if_adicionais',
            field=models.TextField(blank=True, null=True, verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da Empresa Parceira'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
