# Generated by Django 5.2 on 2025-06-27 00:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_alter_parceiros_email_alter_parceiros_if_adicionais_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fazenda',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='fazenda',
            name='usuarios',
            field=models.ManyToManyField(related_name='fazendas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável'),
        ),
    ]
