# Generated by Django 5.2 on 2025-06-17 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receita', '0002_remove_receita_cadastradopor_fazenda_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('parcelas', models.IntegerField(default=1, verbose_name='Número de Parcelas')),
                ('descricao', models.TextField(verbose_name='Descrição da Despesa')),
                ('imposto_renda', models.BooleanField(verbose_name=False)),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('cadastrado_em', models.DateField(verbose_name='Cadastrado Em')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despesa.categoriadespesa', verbose_name='Categoria da Despesa')),
                ('cliente_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.clientefornecedor', verbose_name='Cliente/Fornecedor')),
                ('fazenda_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='receita.fazenda', verbose_name='Fazenda Destino')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_parcela', models.IntegerField(verbose_name='Ordem da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='despesa.despesa')),
            ],
        ),
    ]
