# Generated by Django 5.2 on 2025-06-27 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0004_remove_fazenda_usuarios_fazenda_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Medicamento')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade evalidade =m Estoque')),
                ('validade', models.DateField(verbose_name='Data de Validade')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.fazenda', verbose_name='Fazenda')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['validade'],
            },
        ),
        migrations.CreateModel(
            name='EntradaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Adicionada')),
                ('validade', models.DateField(verbose_name='Data de Validade')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Entrada de Medicamento',
                'verbose_name_plural': 'Entradas de Medicamentos',
                'ordering': ['-validade'],
            },
        ),
        migrations.CreateModel(
            name='SaidaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Retirada')),
                ('data_saida', models.DateField(auto_now_add=True, verbose_name='Data da Saída')),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Saída de Medicamento',
                'verbose_name_plural': 'Saídas de Medicamentos',
                'ordering': ['-data_saida'],
            },
        ),
    ]
