# Generated by Django 5.2.4 on 2025-08-26 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("perfis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Medicamento"
                    ),
                ),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perfis.fazenda",
                        verbose_name="Fazenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="EntradaMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_medicamento",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Custo por Unidade",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(verbose_name="Quantidade Adicionada"),
                ),
                ("validade", models.DateField(verbose_name="Data de Validade")),
                (
                    "data_cadastro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Cadastro"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "cadastrada_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado Por",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicamento.medicamento",
                        verbose_name="Medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Medicamento",
                "verbose_name_plural": "Entradas de Medicamentos",
                "ordering": ["validade"],
            },
        ),
    ]
