# Generated by Django 5.2.4 on 2025-08-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entradamedicamento",
            name="valor_medicamento",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Valor Total"
            ),
        ),
    ]
